apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: go-restro
  name: go-restro
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-restro
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-restro
    spec:
      containers:
        - ports:
            - containerPort: 8000
          resources:
            limits: {}
            requests: {}
          env:
            - name: MY-PORT
              value: "8000"
          volumeMounts: []
          image: go-restro:latest
          name: go-restro
          imagePullPolicy: Never